apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mq-metric-samples-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io    
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/prod/mq-metric-samples
    repoURL: https://github.com/ibm-prod-ref-guide/multi-tenancy-gitops-apps
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
