apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgA9Q5mT5ZT/4P8jDA4m/O22fV8i98CsCOrgrIgToFEvDhnHOcMNsuEC/Zk1afR7nWLO0YcRBikEzkrpaYBV0QGZV5CAF2UTBV5FEU0MDYLN+mhv9KczD11Sumz6/ZI+SscwT/UMoQdsSfzBtqu5h+cKIk3JL/YDG15wOQF3iG4hYGshbJ9AXoX2qNw7Dy/zp3AAvR5sl7ibuuKRFX+vihIsHTt6iUQ/IsKvQ5/P422ttoUgGjD6jRPAG3mNOeu39TqXd/MVvxgHpsl9340YK1NfbfwUICmNR9c7gJOsFIqNnTI+Rf9ROgAdqk+TamsjcppA5xPJJeippVSf1oMiEL96DG2xOrc/Z/3A9MS/NWBgkx0g+oEXIolSm/x61o/tHRJqiqFPv+pTTuKeBkl+EiSezkzDt25JRYvYxH72OWpc7geRq7rLPre1zSiN+2L0ttldHkzcok65iDh0mC/Ohlnde9OfzYgwtIOxYAsTwGYr91KtUyW8PcBw4QXjhOCXZoOo4HPkZh5a4Kj36IOUWyqwnTIZ+jVGn4HigrAguBELnRSt+PhhhdjzR/0+YGapTgIUjuoQOpzwWN1jT7/61FxYloxSFYfdHHMZjJQl+I3b71CqoakXzCMK0xyJ4Bbxw5p57WNYQThvkSFwJwuzHZbJJcIEz2pjGjKT/i1t2++1p5kciIELnR/yUg/rhGdDKdXq8smAvdnBjGa5CSWvQ0nXeqeZCGg7Cc6aCHKPRRcfM23QlQzepmyB
    username: AgA17fxyuDVCojtOqr3hPquxE41T4NAWCkSiG9GAEH4BBUq3OTi9RDWdryWRhHXb7ZXMXh/BCTn8O66AKK8kC8uBRS3Xs80cHsFaXRMMCk839bIi8tN3pqc5tlDM+6ygEqFGUFtYyW4i/8Z1rHk7QRSuLW6D0mch4GU5p2HzGTn2OHodT6QFxJF3IrCalGNmw+M6VkIWkdT6mu0K0Erh5WbS/K4t2GE0GGrGmG59dIUpaZgoM2FRNEG+/Dk6G327zTwqgPxm3GRP5TpwbH4vFXLCGE45Aw7Y5vnpNB8B6duQDGoVVFfcPyOcoUbYvOSiqjhfd5BTKj5sA4Ms75NV+wCwDDQT9wGZzFGwVpm6MlxIT9KHZt+YycDNJqU2p7+Fb93Sf1+uXYqmOJEFynqBa/lI/mddvdK7UjofwPYyZ6Ao56E/UPuHOCtPnucE63VgiA+Yuv+0hv2uCl2sLyOQdtAfEDWIKcQg60NELAoY6EKkS5KsDDuUO3bllt7lBB43iyUnnqIqHxMykHiIx1KTApe5M0Vj5F/AIY1DCUoxIiDTOMZBEpbFq/luWgcuwLO87a+5irZrs/cYMt3TFhoiJyfcbHdXbmi7H65TBiWItudnB/A76zl0NLbSWeRB5zsFQyJu44CEYL60lN2f/kbC1AMjV221Yur2I6ULGosV9dZPbYpnFyz/SIfMZMZoOZB3OfflyzY2eJ9O
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

