apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgCaA0dyaqhtyjEojZcBB7XmUZ0Vwz9B/Zeo3vlwA6mvK5ImCYyOQ5c5lNAAIilA9Ou5EVgKolyDh/Xe+RNm8REujATZR6pAUQ/Xcei7Ac1ZCoqmdT7fitwNvmZVCeap1xq1P//lBRNggv9TVdzeVQC0s/opxlju/7eBbMkIn+48D1Mb5U7ysJo4kaxjOAUwSa461ablrHWpjVbS4cMQUvUEON3T92t5FFYPefdH4wyGpJ9VJM0SxO5XExxVXdoN7rOa/xabkSC1fMn1vRrZxtM6ZleHGOmMsKyCXyy2qPauSB4RXwHNurMrvQelqkzay0sCA6WuqvllUJAbkfiRrd+WCc6ZZ/iEEmh3O4x7mtZAeodvVpRf5XHtv5gIxgs9gHeXA5LCutDJk/9n+r0s+vVcShMfbdNvJV3SAYKDPWKp96ctsJaDnVi1HUytQRErCKC3n+7+hun+qgCw4YC+DtwPe8/EKG6mhrNcZLzyRVkIy3efQ5ZBC+yRqWbJ5NvUfG3u149w2NtvB/KszOALJ3zQemzI6mQhRCxHtM3FfHJTSMJkluoj+9RRumZrLOdikl7+x1nHuN0MJ9REoEqXm3ChapHo2cXpm19n4JXGvdHXW2HadRaKN6I8dmbmncWdHahlqJb4yr/9NPSOlP6If4RVwtTAlrrsiy/ZxKOPus3bdr6yOEKfhnreFDZ4cg0SO/1XNBt3IVaEBTlJOmkP0bjS76jApv/EgCZD7lnTKjvSluzOHUrqKIut
    username: AgBWyp/HxsP8Z5itdQQh1QD0TQInXztW3CnYSXSUtFswJy7uCtQAjJu/5aKPBhYQIDo1LNwoXQkgprj974eWhhoeP4ojkLca146m9o9trBWEVR5YWI5RSwGu49e/uG/tf5bcBrwTkT5m6DP0jbFbNirX9eq2fCAXWg8xMjwSV+RTAG5E7xFEAOlOZLLf4sbIlAzYH9OW58a89YalMEJZqQphj892qLIUnLj7e2y1zhqroPYs9QlkgzCQQK/TdxwzvKbaNK7Yiszvg64Zh6KmJbNBT9LLGE0MzncTHLlT4HHwkwYmvNuU3rbDDP8s3MvYPBe3HzVNRRV0vd08sBfqsoHrRVJiJabR7ac14sTai+d1dqhQ+ayX6Jdv9eArELsmbnnwJLJR6ZDk8WuzGUPSpOk9OJZ0w7vd0ghYYKHxctm00VgRUlY2vTGEnd2s7xWWa3dk9DbYCal+ZE3MyCLqAawikKWxELg11H3Vc3745ZI0t76wSN7rCz0EW5q3TU7xMdK73FYMrYOqv1gQ1027F1Bs2+5k+tU2zCYs5ZoEkWNT2zPEiyERuFDceEIzF5NUEsyvCPzcyt5S8qiOe0GBKdICk2dIcUj8OUCZSzZF7AAuYV228rNZdTSgeLpA7/+T6hJkBRbRZF+HWlH9SMfZTorUKz7dTEQjnv1KsHQyHyu55X0ZLGDPgdBBKmszhbcXGKjvOGdTwytE
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

