apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCjLBy/VgCG2wv4LW6QzMCuPe2hhajzg18nw21HmFIy9p9wvlev6porydXEy6DkpSX06q5/GXBxVDwG2Niq07iMgCJuWzMFAFPivpciR76o5MB/kh0UYTixvtHUBADAiIVFFit+7OhujPu9iaQpmpuB2EHBy1LkIRuggevjW8o8DmlxXdKbdg5/Y6irmsIEO/c9kRukM89bXt+VTZKtkU22IRaK5aDgMakzuw8UemIQCpIxl70Bztnty97N0p/BAjN69e/27e/VqTIsIjbD+Xuzy8imxv8mfXm0QrvMAHiIEdzn3uxZk/72hyRF7ChvMqQoZdrkDlxotPeigSIDILYZKsp4L/AMxGpWv3Noqzk4WStWTAC+pnDqCTSa2oRRyH3yjIczhSl6h5THwqcO1a0ugJJ1TfFUkK0lyUD6O5ynAcAek90CzymPp9mQGcBzT3XcvUpxYuGH2WukWHS98N+1KpWqzXoqTEiZkBA8LMrehRyc8L7mK23uRlBTOZeZL5c2S9Td2pAhT2GaOhN/HigmFcUXOSooBvXEpUDl80dyZrywKK1NS8RLsF/CkrQW143KLKYIFQcDHT5leqDeEIpcruYPMrOOW7523D3/57sH1wf2z02EzohouiCOS4wLjtybIomf9u5uLjMxLFvCnGxSvAysTm31J0YCDenQ9FewIePylcAOniq5SShI/AyMgbYBFBvjsER/jLPslYmB/s96PlCHrrb1f/ImLMl53z6AeYUvnJCOGN5r3O9mYwZbQcD6fwgRhENWBU8Mt4Wtii6Gs43pxlJXrdmfx3O0EokZoBLd9RknUTf+/c4bPnBpAJ6TdtNChbvmYKt4lxe3/AsYbRNcnQs/0Tk1kzybHDnEb0J/zm4FShTFS/dWlYrCPIgmN5yNUvWQQXKxPZO2QonaEZgM09uh2ocpLaZC98EyE1DrVkTCz1SYT0c1s44Uqvo=
    IBM_ENTITLED_REGISTRY_USER: AgADEeaF5DzQSgYMXyYPzFuT4k9aYAvoPrhE2ozUAnapiXVNU2FNX8prwlAjN6/4Bd3VofTcpVRcySBkzOGQT7pKI2NMPfqmW83Fyf81MHjy2QentEAHnr5KT4giIRIjtyNQQwiZOg4N2AkHc2Gje1GBVv5voZPh106sR9Ywajj8FwUr5PBBy/3TF/9C2LpgYG91r+4dsil90JlvjeHh3d4UR772B5v2iMJsTN5BO29frXh8VRO20z+K7O6uccGIiq9XESCRWIuNwv/5M3nj806skqZm7ctWYJKhVMwHN5CSbpkRTW83MaJ2jAJ4/pGOvKG2f3mxKnu7KQRxvRW50Txn88ufefTPCXHKHDT6OG66aHzB4WgsNxprj4ckxCZPBqgbKtajcKF44S4abSLBJBC50S7ghyC2C/j9ovIoDu9xEPwq3kms5ioe5aFFOCcSVY0axsuc0okqcGWyxJNCZ/9ykiYNe9RcSjtQieDo4kq0gFrzrnZrefLDm2SgeBHU+KFj53Im41/X05BS+L7KsJeepD3NrLCfUbhsSlA3QuRRVdHBa8ZtWNB+v0kNdcaaHDCMOrxM2gBWW+JhQroZRSc22exQvut7ctA3UB6SWCgx2ghdB27XOT3NVLNlhDHDjDsmgdT7cq+WPFzK39zzsY7vbILiqD3COF4y1Pk/zWJDngAt9uC9BOPqRc6tO9JVdghPeA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

